/**
 * Markdown Report Template
 *
 * Generates markdown format reports.
 */

import type { ExtendedProjectScore, TrendAnalysis, ReportIssue } from '../reporting.types.js';

/**
 * Severity emoji mapping
 */
const SEVERITY_EMOJI: Record<string, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

/**
 * Status emoji mapping
 */
const STATUS_EMOJI: Record<string, string> = {
  excellent: '✅',
  good: '👍',
  fair: '😐',
  poor: '👎',
  critical: '⚠️',
};

/**
 * Trend emoji mapping
 */
const TREND_EMOJI: Record<string, string> = {
  improving: '📈',
  stable: '➡️',
  declining: '📉',
};

/**
 * Markdown report template generator
 */
export class MarkdownTemplate {
  /**
   * Generate a complete markdown report
   *
   * @param score - Project score to report
   * @param trend - Optional trend analysis
   * @returns Markdown formatted report
   */
  static generate(score: ExtendedProjectScore, trend?: TrendAnalysis): string {
    const lines: string[] = [];

    // Header
    lines.push('# 📊 Code Quality Report');
    lines.push('');
    lines.push(`**Project:** \`${score.projectPath}\``);
    lines.push(`**Generated:** ${score.timestamp.toLocaleString()}`);
    if (score.commit) {
      lines.push(`**Commit:** \`${score.commit}\``);
    }
    if (score.branch) {
      lines.push(`**Branch:** \`${score.branch}\``);
    }
    lines.push('');

    // Overall Score Section
    lines.push('## 🎯 Overall Score');
    lines.push('');
    lines.push(`### ${this.getScoreDisplay(score.overall)}`);
    lines.push('');
    lines.push(this.generateProgressBar(score.overall));
    lines.push('');

    // Trend Section (if available)
    if (trend) {
      lines.push('## 📈 Trend Analysis');
      lines.push('');
      lines.push(this.generateTrendSection(trend));
      lines.push('');
    }

    // Dimensions Section
    lines.push('## 📐 Dimensions');
    lines.push('');
    lines.push('| Dimension | Score | Status | Issues |');
    lines.push('|-----------|-------|--------|--------|');

    for (const [key, dimension] of Object.entries(score.dimensions)) {
      const statusIcon = STATUS_EMOJI[dimension.status] || '❓';
      lines.push(
        `| ${key} | **${dimension.score}**/100 | ${statusIcon} ${dimension.status} | ${dimension.issues.length} |`
      );
    }
    lines.push('');

    // Dimension Details
    for (const [key, dimension] of Object.entries(score.dimensions)) {
      if (dimension.issues.length > 0) {
        lines.push(`### ${key}`);
        lines.push('');
        lines.push(`**Score:** ${dimension.score}/100`);
        lines.push(`**Weight:** ${dimension.weight}`);
        lines.push('');

        for (const issue of dimension.issues) {
          lines.push(this.generateIssueBlock(issue));
        }
        lines.push('');
      }
    }

    // All Issues Section (grouped by severity)
    if (score.issues.length > 0) {
      lines.push('## ⚠️ Issues');
      lines.push('');

      const grouped = this.groupIssuesBySeverity(score.issues);
      for (const [severity, issues] of Object.entries(grouped)) {
        if (issues.length > 0) {
          lines.push(`### ${SEVERITY_EMOJI[severity] || ''} ${severity.charAt(0).toUpperCase() + severity.slice(1)} (${issues.length})`);
          lines.push('');
          for (const issue of issues) {
            lines.push(this.generateIssueBlock(issue));
          }
          lines.push('');
        }
      }
    }

    // Recommendations Section
    lines.push('## 💡 Recommendations');
    lines.push('');
    const recommendations = this.generateRecommendations(score);
    for (const rec of recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push('');

    // Footer
    lines.push('---');
    lines.push('*Generated by [Daemon](https://github.com/Pamacea/daemon)*');

    return lines.join('\n');
  }

  /**
   * Generate a markdown summary for quick viewing
   *
   * @param score - Project score
   * @returns Brief markdown summary
   */
  static generateSummary(score: ExtendedProjectScore): string {
    const lines: string[] = [];

    lines.push(`**Score:** ${this.getScoreDisplay(score.overall)}`);
    lines.push('');

    for (const [key, dimension] of Object.entries(score.dimensions)) {
      lines.push(`- **${key}:** ${dimension.score}/100 ${STATUS_EMOJI[dimension.status] || ''}`);
    }

    if (score.issues.length > 0) {
      lines.push('');
      const critical = score.issues.filter(i => i.severity === 'critical').length;
      const high = score.issues.filter(i => i.severity === 'high').length;
      lines.push(`**Issues:** ${critical} critical, ${high} high, ${score.issues.length - critical - high} other`);
    }

    return lines.join('\n');
  }

  /**
   * Generate markdown table for dimension scores
   *
   * @param score - Project score
   * @returns Markdown table
   */
  static generateDimensionTable(score: ExtendedProjectScore): string {
    const lines: string[] = [];

    lines.push('| Dimension | Score | Status |');
    lines.push('|-----------|-------|--------|');

    for (const [key, dimension] of Object.entries(score.dimensions)) {
      const statusIcon = STATUS_EMOJI[dimension.status] || '❓';
      lines.push(`| ${key} | ${dimension.score}/100 | ${statusIcon} ${dimension.status} |`);
    }

    return lines.join('\n');
  }

  /**
   * Generate issue list grouped by severity
   *
   * @param issues - Array of issues
   * @returns Markdown formatted issue list
   */
  static generateIssueList(issues: ReportIssue[]): string {
    const grouped = this.groupIssuesBySeverity(issues);
    const lines: string[] = [];

    for (const [severity, severityIssues] of Object.entries(grouped)) {
      if (severityIssues.length > 0) {
        lines.push(`### ${SEVERITY_EMOJI[severity] || ''} ${severity.charAt(0).toUpperCase() + severity.slice(1)}`);
        lines.push('');

        for (const issue of severityIssues) {
          lines.push(this.generateIssueBlock(issue));
        }
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate trend analysis section
   */
  private static generateTrendSection(trend: TrendAnalysis): string {
    const lines: string[] = [];

    // Overall trend
    const overallTrend = trend.overallTrend;
    lines.push(`- **Overall:** ${overallTrend.current}/100 ${TREND_EMOJI[overallTrend.trend] || ''} (${overallTrend.delta >= 0 ? '+' : ''}${overallTrend.delta})`);
    lines.push(`- **Velocity:** +${trend.velocity} points/snapshot`);

    if (trend.regressions.length > 0) {
      lines.push('');
      lines.push(`**⚠️ Regressions detected:** ${trend.regressions.length}`);
      for (const reg of trend.regressions) {
        lines.push(`  - ${reg.dimension}: -${reg.drop} points (${reg.severity})`);
      }
    }

    if (trend.improvements.length > 0) {
      lines.push('');
      lines.push(`**✅ Improvements:** ${trend.improvements.length}`);
      for (const imp of trend.improvements) {
        lines.push(`  - ${imp.dimension}: +${imp.increase} points`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Generate a single issue block
   */
  private static generateIssueBlock(issue: ReportIssue): string {
    const icon = SEVERITY_EMOJI[issue.severity] || '•';
    const location = issue.file
      ? `[\`${issue.file}${issue.line ? ':' + issue.line : ''}\`](${issue.file})`
      : '';

    let block = `#### ${icon} ${issue.category}\n`;
    block += `${issue.message}\n`;

    if (location) {
      block += `\n**Location:** ${location}\n`;
    }

    if (issue.suggestion) {
      block += `\n**Suggestion:** ${issue.suggestion}\n`;
    }

    return block;
  }

  /**
   * Generate a text-based progress bar
   */
  private static generateProgressBar(score: number): string {
    const filled = Math.round(score / 5);
    const empty = 20 - filled;
    const bar = '█'.repeat(filled) + '░'.repeat(empty);
    const color = this.getScoreColor(score);
    return `<span style="color:${color}">${bar}</span> ${score}/100`;
  }

  /**
   * Get score display with emoji
   */
  private static getScoreDisplay(score: number): string {
    const emoji = score >= 90 ? '🌟' : score >= 70 ? '👍' : score >= 50 ? '😐' : score >= 30 ? '👎' : '⚠️';
    return `${emoji} **${score}** / 100`;
  }

  /**
   * Get color for score
   */
  private static getScoreColor(score: number): string {
    if (score >= 90) return '#10b981';
    if (score >= 70) return '#22c55e';
    if (score >= 50) return '#eab308';
    if (score >= 30) return '#f97316';
    return '#ef4444';
  }

  /**
   * Group issues by severity
   */
  private static groupIssuesBySeverity(issues: ReportIssue[]): Record<string, ReportIssue[]> {
    const grouped: Record<string, ReportIssue[]> = {
      critical: [],
      high: [],
      medium: [],
      low: [],
      info: [],
    };

    for (const issue of issues) {
      const severity = issue.severity.toLowerCase();
      if (grouped[severity]) {
        grouped[severity].push(issue);
      }
    }

    return grouped;
  }

  /**
   * Generate recommendations based on score
   */
  private static generateRecommendations(score: ExtendedProjectScore): string[] {
    const recommendations: string[] = [];

    // Analyze dimensions
    for (const [key, dimension] of Object.entries(score.dimensions)) {
      if (dimension.score < 50) {
        recommendations.push(`🔴 Focus on **${key}** - Score is ${dimension.score}/100`);
      } else if (dimension.score < 70) {
        recommendations.push(`🟡 Improve **${key}** - Score is ${dimension.score}/100`);
      }
    }

    // Check for critical issues
    const criticalIssues = score.issues.filter(i => i.severity === 'critical');
    if (criticalIssues.length > 0) {
      recommendations.push(`⚠️ Address ${criticalIssues.length} critical issue(s) immediately`);
    }

    // Check for high severity issues
    const highIssues = score.issues.filter(i => i.severity === 'high');
    if (highIssues.length > 0) {
      recommendations.push(`🔠 Fix ${highIssues.length} high severity issue(s) soon`);
    }

    // Add positive reinforcement
    if (score.overall >= 80) {
      recommendations.push('✅ Great job maintaining high code quality!');
    } else if (score.overall >= 60) {
      recommendations.push('💪 Keep working on code quality - you\'re on the right track!');
    }

    return recommendations;
  }
}
