//! Test generators for Rust projects
//!
//! Provides framework-specific test generation

use crate::{Result, RustFramework, TestPlan, TestFile};
use std::path::Path;

/// Test generator for Rust projects
pub struct TestGenerator {
    framework: RustFramework,
}

impl TestGenerator {
    /// Create a new test generator for the given framework
    pub fn new(framework: RustFramework) -> Self {
        Self { framework }
    }

    /// Generate unit tests for the project
    pub fn generate_unit_tests(&self, project_path: &str) -> Result<Vec<TestFile>> {
        let path = Path::new(project_path);
        let mut tests = Vec::new();

        // Find Rust source files and generate tests
        for entry in walkdir::WalkDir::new(path.join("src"))
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path().extension() == Some(std::ffi::OsStr::new("rs"))
                    && !e.path().to_string_lossy().ends_with("_test.rs")
            })
        {
            let test_name = format!("{}_test", entry.file_name().to_string_lossy());
            let test_path = format!("src/{}", test_name);

            tests.push(TestFile {
                path: test_path,
                description: format!("Unit tests for {}", entry.file_name().to_string_lossy()),
                content: self.generate_test_content(entry.path())?,
            });
        }

        Ok(tests)
    }

    /// Generate integration tests for the project
    pub fn generate_integration_tests(&self, project_path: &str) -> Result<Vec<TestFile>> {
        let path = Path::new(project_path);
        let tests_dir = path.join("tests");

        // Create tests directory if it doesn't exist
        std::fs::create_dir_all(&tests_dir)?;

        let mut tests = Vec::new();

        // Generate API integration tests based on framework
        match &self.framework {
            RustFramework::Axum => {
                tests.push(TestFile {
                    path: "tests/api_integration.rs".to_string(),
                    description: "API integration tests".to_string(),
                    content: include_str!("templates/axum_handler_unit.rs").to_string(),
                });
            }
            RustFramework::ActixWeb | RustFramework::Actix => {
                tests.push(TestFile {
                    path: "tests/api_integration.rs".to_string(),
                    description: "API integration tests".to_string(),
                    content: include_str!("templates/actix_handler_unit.rs").to_string(),
                });
            }
            _ => {
                tests.push(TestFile {
                    path: "tests/integration.rs".to_string(),
                    description: "Basic integration tests".to_string(),
                    content: include_str!("templates/vanilla_unit.rs").to_string(),
                });
            }
        }

        Ok(tests)
    }

    /// Generate a complete test plan
    pub fn generate_plan(&self, project_path: &str) -> Result<TestPlan> {
        Ok(TestPlan {
            unit_tests: self.generate_unit_tests(project_path)?,
            integration_tests: self.generate_integration_tests(project_path)?,
            e2e_tests: None,
        })
    }

    fn generate_test_content(&self, source_path: &Path) -> Result<String> {
        let module_name = source_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("module");

        let content = format!(
            r#"//! Unit tests for {module_name}
//!
//! Generated by daemon-rust

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_example() {{
        // TODO: Add actual tests
        assert!(true);
    }}
}}
"#,
            module_name = module_name
        );

        Ok(content)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let generator = TestGenerator::new(RustFramework::Axum);
        assert!(matches!(generator.framework, RustFramework::Axum));
    }
}
